---

- name: Target is VM?
  set_fact:
    image_type: vm
  when: _apb_plan_id == 'url'

- name: Target is Template?
  set_fact:
    image_type: template
  when: _apb_plan_id == 'url-template'

- name: Change project to {{ namespace }}
  command: "oc project {{ namespace }}"

- name: Delete VM resources
  command: "oc delete vm -l import-vm-apb/transaction_id={{ _apb_service_instance_id }} --ignore-not-found=true"
  when: image_type == "vm"

- name: Delete Template resources
  block:
    - command: "oc login --insecure-skip-tls-verify=true -u {{ admin_user }} -p {{ admin_password }}"
    - command: "oc delete template -l import-vm-apb/transaction_id={{ _apb_service_instance_id }} -n openshift --ignore-not-found=true"
    - name: Get current relist count"
      command: "oc get clusterservicebroker template-service-broker -o jsonpath='{.spec.relistRequests}'"
      register: current_relist_count
    - command: "oc patch clusterservicebroker template-service-broker -p '{\"spec\": {\"relistRequests\": {{ current_relist_count.stdout|int + 1 }} }}'"
      ignore_errors: yes
  when: image_type == "template"
  
- name: Delete PVC
  command: "oc delete pvc -l import-vm-apb/transaction_id={{ _apb_service_instance_id }} --ignore-not-found=true"
