- name: Playbook to import the virtual machine disk
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: import-from-url
    when: _apb_plan_id == 'url' or _apb_plan_id == 'url-template'
  - role: provision-v2v
    when: _apb_plan_id == 'vmware' or _apb_plan_id == 'vmware-template'
    
  vars:
    action: provision
    cluster: openshift
