apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ image_type }}-{{ vm_name }}-disk-01"
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "{{ disk_image_url }}"
spec:
{% if storage_class is defined %}
  storageClassName: {{ storage_class }}
{% endif %}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "{{ size_bytes|int }}"
