apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ vm_name }}-disk-01"
  annotations:
    kubevirt.io/storage.import.endpoint: "{{ disk_image_url }}"
spec:
  storageClassName: kubevirt
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "{{ size_bytes|int }}"
